### ISSUE TITLE
status 503

### ISSUE THREAD

**Issue by Froshman** [hinzwifi/MuskAPI#1]
I'm getting status 503 for GET random:

Request URL: https://muskapi.herokuapp.com/api/random
Request Method: GET
Status Code: 503 Service Unavailable

**Comment by Froshman** [comment]
seems to work now (:
got: 
{"message":{"type":"success","quoteId":"7f984587-7571-42cc-8973-083fa3449863","quote":"Patience is a virtue, and I'm learning patience. It's a tough lesson.","URL":"https://muskapi.herokuapp.com/api/quote/7f984587-7571-42cc-8973-083fa3449863"}}

**Comment by hinzwifi** [comment]
Hello @Froshman 
I slept kinda early and I forgot to add the .env in heroku last night. As you can see it is now working.

Thank you for visiting this project.
